Repository opslab/aws-eks-infra, pull requests merged in 2020-11, with the labels that each got.

#2 feat: vpc module added
  main.tf
  variables.tf
Labels: enhancement

#3 Add Key_Pair module
  main.tf
  variables.tf
Labels: bug, enhancement

#6 feat: add README
  README.md
  terraform.tf
Labels: enhancement, good first issue

#7 feat: eks added
  main.tf
  variables.tf
Labels: enhancement, help wanted

#9 Fix/mapusers
  variables.tf
Labels: bug

#10 fix: variable
  main.tf
Labels: bug

#12 feat: change node type to spot instance
  main.tf
  variables.tf
Labels: enhancement, help wanted

#13 Fix/module
  main.tf
Labels: bug, good first issue

#14 testing
  README.md
Labels: documentation, enhancement

#21 Feat/extdns
  README.md
  main.tf
  variables.tf
Labels: enhancement, help wanted

#22 feat: Add ALB Ingress Controller
  README.md
  main.tf
  terraform.tf
  variables.tf
Labels: enhancement

#23 fix: Alb ingress
  main.tf
Labels: bug

#24 feat: database subnet added
  README.md
  main.tf
  variables.tf
Labels: enhancement

#26 fix: rds_subnet_group
  main.tf
Labels: bug, invalid

#27 fix: security group rds update
  main.tf
Labels: enhancement

#28 feat: EKS security Group output
  README.md
  main.tf
  outputs.tf
Labels: bug, enhancement

#29 fix: use source sg id instead of cidr block
  main.tf
Labels: enhancement
